--- #YAML:1.0
name: DateTime-Format-Excel
version: 0.26
license: perl
distribution_type: module
requires:
  DateTime: 0.07
  perl: 5.6.0
recommends: {}
build_requires:
  Test::More: 0.47
conflicts: {}
generated_by: Module::Build version 0.16
