--- #YAML:1.0
build_requires:
  Test::More: 0.47
  Test: 1.23
conflicts: {}
distribution_type: module
license: perl
name: DateTime-Format-Excel
recommends:
  Test::Pod: 0.95
  Test::Signature: 1.03
requires:
  DateTime::Duration: 0
  DateTime: 0.08
  Carp: 1.01
version: 0.27
generated_by: docmaker version 0.89
