---
abstract: 'Convert between DateTime and Excel dates.'
author:
  - "Originally written by Iain Truskett <spoon@cpan.org>, who died on\nDecember 29, 2003."
  - "Maintained by Dave Rolsky <autarch@urth.org> and, since 2010-06-01, by \nAchim Bursian <aburs@cpan.org>."
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-Excel
provides:
  DateTime::Format::Excel:
    file: lib/DateTime/Format/Excel.pm
    version: 0.31
requires:
  DateTime: 0.1705
  Test::More: 0.47
resources:
  license: http://dev.perl.org/licenses/
version: 0.31
