--- #YAML:1.0
name: DateTime-Format-Excel
version: 0.2901
license: perl
distribution_type: module
requires:
  DateTime: 0.1705
  Test::More: 0.47
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Format::Excel:
    file: lib/DateTime/Format/Excel.pm
    version: 0.2901
generated_by: Module::Build version 0.21
